<?php

namespace api\modules\v6\controllers;

use Yii;
use yii\db\Query;
use yii\helpers\Response;
use yii\rest\ActiveController;

class AreaController extends ActiveController
{

    public $modelClass = 'api\modules\v6\models\UserDating';

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $actions = parent::actions();
        unset($actions['index'],$actions['update'],$actions['view'],$actions['create'],$actions['delete']);
        return $actions;
    }

    public function actionIndex(){

        /*$user_id = Yii::$app->request->get('user_id');
        if(!$user_id){
            Response::show('201','error','用户编号不能为空');
        }

        $sex = (new Query())->select('sex')->from('pre_user')->where(['id'=>$user_id])->one();
        if($sex['sex'] == 1){
            $sex['sex'] = 0;
        }else{
            $sex['sex'] = 1;
        }*/

        //$model = $this->modelClass;
        $model = (new Query())->select('address as area')
            ->from('pre_user_profile as p')
            ->leftJoin('{{%user}}', 'pre_user.id = p.user_id ')
            //->where(['flag'=>2,'p.status'=>2,'sex'=>$sex])
            ->where(['flag'=>2,'p.status'=>2])
            ->groupBy('area')->all();

        if($model){
            $list = array();
            $data['value'] = array();
            foreach($model as $v=>$k){

                array_push($data['value'],explode(' ',$k['area'])[0]);
            }
            //去除重复数组元素
            array_push($list,array_unique($data['value']));
            $row = array();
            foreach($list as $li){
                $word1 = '省';
                $word2 = '市';
                $word3 = '区';
                foreach($li as $k=>$v){

                    if($v == 'NY'){
                        $v = '纽约';
                    }
                    $li1 = strpos($v,$word1);
                    $li2 = strpos($v,$word2);
                    $li3 = strpos($v,$word3);
                    if(!$li1 && !$li2 && !$li3){
                        $row[] = $v;
                    }

                }
            }
            Response::show('200','成功',$row);
        }

    }
}