<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/9/5
 * Time: 10:11
 */

namespace api\modules\v6\controllers;

use Yii;
use yii\db\Query;
use yii\helpers\Response;
use yii\rest\ActiveController;

class DatingNeedCoinController extends ActiveController
{

    public $modelClass = 'api\modules\v6\models\DatingNeedCoin';

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $action = parent::actions();
        unset($action['index'],$action['view'],$action['create'],$action['update'],$action['delete']);
        return $action;
    }

    public function actionView($id){

        $model = $this->findModel($id);
        $level = $model->groupid;
        $sex = $model->sex;

        //一个月觅约一次
        $dating = (new Query())->select('expire,status')->from('{{%app_selfdating}}')->where(['user_id'=>$id])->one();
        $time = time();
        if($dating && $time < $dating['expire'] && $dating['status'] == 0){
            Response::show('201','一个月只能发布觅约一次');
        }
        $jiecaocoin = (new Query())->select('jiecao_coin')->from('{{%user_data}}')->where(['user_id'=>$id])->one();
        //男：等级为1 每次觅约需支付98元，等级为2 首次觅约免费，之后每次支付98
        if($level == 1 && $sex == 0 ){
            if($jiecaocoin['jiecao_coin'] < 98 ){
                Response::show('201','觅约需98心动币，您的余额不足');
            }else{
                Response::show('200','每月可发布一次觅约，每次98心动币');
            }
        }elseif($level == 2 && $sex == 0) {
            $dating2 = (new Query())->select('')->from('{{%app_selfdating}}')->where(['user_id' => $id,'status'=>0])->one();
            //免费一次
            if ($dating2) {
                if ($jiecaocoin['jiecao_coin'] < 98) {
                    Response::show('201', '觅约需98心动币，您的余额不足');
                }else{
                    Response::show('200','每月可发布一次觅约，每次98心动币');
                }
            }else{
                Response::show('200','普通会员首次觅约免费');
            }
        }else{
            Response::show('200','您一个月只需发布一次觅约');
        }
    }

    protected function findModel($id)
    {
        $modelClass = $this->modelClass;
        if (($model = $modelClass::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}