<?php
namespace api\modules\v6\controllers;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\rest\ActiveController;
use yii\helpers\Response;

class UserDatingController extends ActiveController
{

    public $modelClass = 'api\modules\v6\models\UserDating';
    public $serializer = [
        'class'     =>  'yii\rest\Serializer',
        'collectionEnvelope' => 'items'
    ];

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $actions = parent::actions();
        unset($actions['index'], $actions['update'], $actions['view'], $actions['create'], $actions['delete']);
        return $actions;
    }
    public function actionIndex()
    {

        $user_id = $_GET['user_id'];
        $res = (new Query())->select('sex')->from('{{%user}}')->where(['id' => $user_id])->one();

        if (!$res) {
            Response::show('201', '用户不存在');
        } else {
            if ($res['sex'] == 0) {
                $res['sex'] = 1;
            } else {
                $res['sex'] = 0;
            }

            $model = $this->modelClass;
            $time = isset($_GET['time']) ? $_GET['time'] : '';
            $age = isset($_GET['age']) ? $_GET['age'] : null;
            $marry = isset($_GET['marry']) ? $_GET['marry'] : null;
            $address = isset($_GET['address']) ? $_GET['address'] : '';

            $where = ' pre_user_profile.status = 2 and pre_user_profile.flag =2 and sex = ' . $res['sex'];

            //查询24小时内的觅约
            if (!empty($time) && $time == 1) {
                $t = time() - 86400;
                $where .= ' and updated_at > ' . $t;
            }


            if ($age !== null) {
                $ages = explode('~', $age);
                $len = count($ages);
                if ($len == 2) {
                    $sage = $ages[0];
                    $lage = $ages[1];
                    $where .=  ' and (year(now())-year(`birthdate`)) >= '.$sage.' and (year(now())-year(`birthdate`)) < '.$lage;
                } else {
                    $lage = $ages[0];
                    //查询小于等于18岁的
                    if($lage == 18 ){
                        $where .= " and (year(now())-year(`birthdate`)) <= " . $lage;
                    }elseif($lage == 30 ){
                        //查询大于等于30岁的
                        $where .= " and (year(now())-year(`birthdate`)) >= " . $lage;
                    }else{
                        Response::show('201','年龄不正确');
                    }
                }
            }

            if ($marry !== null && $marry == '单身') {
                $where .= ' and is_marry = 0';
            } elseif ($marry !== null && $marry == '有男/女朋友') {
                $where .= ' and is_marry = 1 ';
            } elseif ($marry !== null && $marry == '已婚') {
                $where .= ' and is_marry = 2';
            }

            if (!empty($address)) {

                $address = $address."%";
                $where .= ' and address like \'' . $address.'\'';
            }
            //return $where;
            $query = $model::find()
                ->select('pre_user_profile.*,pre_user.sex,pre_user.avatar')
                ->leftJoin('{{%user}}', 'pre_user.id = pre_user_profile.user_id ')
                ->where($where);

            return new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                    'pageSize' => 15,
                ],
                'sort' => [
                    'defaultOrder' =>
                        ['updated_at' => SORT_DESC,],
                ],
            ]);

        }
    }
        public function findModel($id){
            $modelClass = $this->modelClass;
            if (($model = $modelClass::findOne($id)) !== null) {
                return $model;
            } else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
        }
    }
