<?php

namespace frontend\controllers;

use backend\modules\exciting\models\Website;
use frontend\models\CollectingFilesText;
use Yii;
use frontend\models\FlopContentDataWei;
use backend\modules\flop\models\Flop;
use backend\modules\flop\models\FlopContent;
use frontend\models\FlopYanZhen;
use yii\db\Query;
use yii\helpers\ArrayHelper;
use yii\myhelper\Jssdk;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\myhelper\Address;
use yii\myhelper\BiHua;

class WFlopController extends Controller
{

    public $enableCsrfValidation = false;
    public $layout = 'basic';
    public $flag;
    public $session;
    public $web_url;
    public $openid;
    public $cookie;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup', 'develop', 'help'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout','encryption'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],

        ];
    }

    public function init()
    {

        $this->web_url = "http://13loveme.com/w-flop/";

        $cookies = Yii::$app->response->cookies;
        $cookie = Yii::$app->request->cookies;

        if(empty($cookie->get('flag2'))){
            $cookies->add(new \yii\web\Cookie([
                'name' => 'flag2',
                'value' => time().rand(10000,99999),
                'expire'=>time()+3600*24*365,
            ]));
        }

        $this->flag = $cookie->getValue('flag2');
        $this->openid = Yii::$app->request->get('openid');

        if(empty($this->openid)){

            return $this->redirect('http://13loveme.com/w-flop/wei-flop');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionShowMsg($number,$id){

        $openid = Yii::$app->request->get('openid');
        $session = Yii::$app->session;
        if(!$session->isActive){
            $session->open();
        }
        $session->set('flop_number',$id);

        $model = CollectingFilesText::findOne($number);
        $imgs = $model->imgs;
        Yii::$app->session->setFlash('skip_teach','skip_teach');
        return $this->render('show-msg',['model'=>$model,'imgs'=>$imgs,'openid'=>$openid,]);

    }

    public function actionWeiFlop(){
        $callback="http://13loveme.com/w-flop/weiflopuserinfo";
        $options = array(
            'appid'=>Yii::$app->params['appid'],
        );

        $callback = urlencode($callback);
        $url = "https://open.weixin.qq.com/connect/oauth2/authorize?appid={$options['appid']}&redirect_uri={$callback}&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect";

        return $this->redirect($url);

    }
    public function actionWeiflopuserinfo(){

        $options = array(
            'appid'=>Yii::$app->params['appid'],
            'appsecret'=>Yii::$app->params['appsecret'],

        );
        $data['code'] = Yii::$app->request->get('code');
        $data['state'] = Yii::$app->request->get('state');

        if(!empty($data['code'])){

            $url = "https://api.weixin.qq.com/sns/oauth2/access_token?appid={$options['appid']}&secret={$options['appsecret']}&code={$data['code']}&grant_type=authorization_code";

            $access = file_get_contents($url);

            $result = json_decode($access);

            $openid = $result->openid;

            $noteUrl = 'http://13loveme.com/w-flop/area?openid='.$openid;

            return $this->redirect($noteUrl);

        }

    }

    public function actionWeiFlops(){
        $flag = Yii::$app->request->get('flag');
        $callback="http://13loveme.com/w-flop/weiflopuser?flag=".$flag;
        $options = array(
            'appid'=>Yii::$app->params['appid'],
        );

        $callback = urlencode($callback);
        $url = "https://open.weixin.qq.com/connect/oauth2/authorize?appid={$options['appid']}&redirect_uri={$callback}&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect";

        return $this->redirect($url);

    }
    public function actionWeiflopuser(){

        $options = array(
            'appid'=>Yii::$app->params['appid'],
            'appsecret'=>Yii::$app->params['appsecret'],

        );
        $data['code'] = Yii::$app->request->get('code');
        $data['state'] = Yii::$app->request->get('state');

        if(!empty($data['code'])){

            $url = "https://api.weixin.qq.com/sns/oauth2/access_token?appid={$options['appid']}&secret={$options['appsecret']}&code={$data['code']}&grant_type=authorization_code";

            $access = file_get_contents($url);

            $result = json_decode($access);

            $openid = $result->openid;

            $noteUrl = 'http://13loveme.com/w-flop/flop-list?openid='.$openid.'&flag='.Yii::$app->request->get('flag');

            return $this->redirect($noteUrl);

        }

    }

    public function actionFlopList($flag){
        
        $openid = Yii::$app->request->get('openid');

        $flopData = new FlopContentDataWei();
        $model = $flopData::find()->where(['openid'=>$openid,'flag'=>$flag])->asArray()->all();
        $girlPhotoModel = Website::find()->with('photo')->asArray();
        $girlPhoto = $girlPhotoModel->where(['website_id'=>3])->one();
        $count = $flopData::find()->where(['openid'=>$openid,'is_evaluate'=>0,'share'=>1])->count();

        $jssdk = new Jssdk();
        $signPackage = $jssdk->getSignPackage();

        Yii::$app->session->setFlash('skip_teach','skip_teach');

        if($flag!=$this->flag){
            
            return $this->render('flop-list-share',[
                'web_url'=>$this->web_url,
                'model'=>$model,'girlPhoto'=>$girlPhoto['photo']
            ]);
        }

        return $this->render('flop-list',[
            'web_url'=>$this->web_url,
            'model'=>$model,
            'flag'=>$this->flag,
            'signPackage'=>$signPackage,
            'openid'=>$openid,
            'count'=>$count,'girlPhoto'=>$girlPhoto['photo']
        ]);
    }

    public function actionHistory(){//历史记录

        $openid = Yii::$app->request->get('openid');

        $model = (new Query())->select('id,GROUP_CONCAT(priority) as priority,created_at,flag')->from('pre_flop_content_data_wei')->where(['openid'=>$openid,'share'=>1])->groupBy('flag')->orderBy('created_at desc');

        $photos = Yii::$app->tools->Pagination($model);
        Yii::$app->session->setFlash('skip_teach','skip_teach');
        return $this->render('history',[
            'model'=>$photos['result'],
            'pages' => $photos['pages'],
            'web_url'=>$this->web_url,
            'openid'=>$openid,
        ]);
    }

    public function actionHistoryDetail(){//历史记录详情

        $openid = Yii::$app->request->get('openid');
        $priority = urldecode(Yii::$app->request->get('priority'));
        $flag = Yii::$app->request->get('flag');

        $priority = explode(',',$priority);

        $query = (new Query())->from('pre_flop_content_data_wei')->where(['in','priority',$priority])->andWhere(['flag'=>$flag])->all();
        Yii::$app->session->setFlash('skip_teach','skip_teach');
        return $this->render('history-detail',[
            'model'=>$query,
            'web_url'=>$this->web_url,
            'openid'=>$openid,
        ]);
    }

    protected function checkEvaluate($openid){

        $query = (new Query())->from('pre_flop_content_data_wei')->where(['openid'=>$openid,'is_evaluate'=>0,'share'=>1])->all();
        return $query;
    }

    public function actionComments(){
        
        $openid = Yii::$app->request->get('openid');
        $post = Yii::$app->request->post();
        
        if(!empty($post)){
            $dataWei = new FlopContentDataWei();
            $query = $dataWei::findOne($post['id']);
            $query->comments_content = $post['content'];
            $query->comments_evaluate= $post['evaluate'];
            $query->comments_dated = $post['dated'];
            $query->is_evaluate = 1;
            $query->update();
        }
        $checkEvaluate = self::checkEvaluate($openid);

        Yii::$app->session->setFlash('skip_teach','skip_teach');

        if(!empty($checkEvaluate)){
            return $this->render('comments',['model'=>$checkEvaluate,'openid'=>$openid,]);
        }
        return $this->redirect('area?web_url='.$this->web_url.'&openid='.$openid);
    }

    public function actionAddComments($openid){

        $content = Yii::$app->request->post('add-comments');
        $id = Yii::$app->request->post('id');
        $type = Yii::$app->request->post('type');

        $back_url=Yii::$app->request->referrer;
        if($type==1301){
            Yii::$app->db->createCommand()->update("{{%flop_content_data_wei}}",['comments_content'=>$content],['id'=>$id])->execute();
        }else{
            Yii::$app->db->createCommand()->update("{{%flop_content_data_wei}}",['comments_add_content'=>$content],['id'=>$id])->execute();
        }

        Yii::$app->session->setFlash('skip_teach','skip_teach');

        return $this->redirect($back_url.'?openid='.$openid);
    }

    public function actionIndex(){

        $openid = Yii::$app->request->get('openid');
        return $this->render('index',['web_url'=>$this->web_url,'openid'=>$openid,]);
    }


    public function actionGreat(){
        $openid = Yii::$app->request->get('openid');
        return $this->render('great',['area'=>'上海','web_url'=>$this->web_url,]);
    }

    public function actionAreaChoice(){
        $openid = Yii::$app->request->get('openid');
        $address = new Address();
        $local =  $address->getAddress();
        if(empty($local)){$local =  '未知位置';}
        $model = ArrayHelper::map(Flop::find()->where('id!=49')->andWhere('id!=118')->andWhere("area!='$local'")->andWhere(['sex'=>0])->orderBy('content ASC')->all(),'area','area');
        Yii::$app->session->setFlash('skip_teach','skip_teach');
        return $this->render('area-choice',['area'=>$local,'model'=>$model,'web_url'=>$this->web_url,'openid'=>$openid]);
    }

    /*区域选择*/
    public function actionAjaxArea($local='',$type=100){

        $pre_url = Yii::$app->params['imagetqlmm'];
        $session = Yii::$app->session;
        if(!$session->isActive){
            $session->open();
        }
        $openid = Yii::$app->request->get('openid');
        $model = (new Query())->select('flop_id')->from('pre_flop_limit_wei')->where(['openid'=>$openid,'status'=>1])->all();
        $exists = ArrayHelper::map($model,'flop_id','flop_id');

        if($type==0){
            /*男神或者精选*/
            $query =FlopContent::find()->where(['not in', 'id', $exists])->andWhere(['flop_id'=>118,'sex'=>0])->orWhere("like_count>10")->andWhere(['sex'=>0])->asArray()->all();
            return json_encode($query[mt_rand(0,count($query)-1)]);
        }elseif($type==2){
            /*最新*/
            $query =FlopContent::find()->where(['not in', 'id', $exists])->andWhere(['>','created_at',time()-86400*5])->andWhere('flop_id!=118')->andWhere(['sex'=>0])->asArray()->all();
            return json_encode($query[mt_rand(0,count($query)-1)]);
        }else {
            if (!empty($session->get('flop_number'))) {
                $query = FlopContent::find()->where(['id' => $session->get('flop_number')])->asArray()->one();
                $session->set('flop_number', '');
            } else {
                $query = FlopContent::find()->where(['area' => $local, 'is_cover' => 1, 'sex' => 0])->andWhere(['not in', 'id', $exists])->asArray()->all();
                /* $random = rand(1, 2);//随机选择，最新发布的出现概率大一点
                 if ($random == 1) {

                     $query = FlopContent::find()->where(['area' => $local, 'is_cover' => 1, 'sex' => 0])->andWhere(['not in', 'id', $exists])->andWhere('nope_count<34')->asArray()->all();
                     if (empty($query)) {
                         $query = FlopContent::find()->where(['area' => $local, 'is_cover' => 1, 'sex' => 0])->andWhere(['not in', 'id', $exists])->asArray()->all();
                     }
                 } else {

                     $query = FlopContent::find()->where(['area' => $local, 'is_cover' => 1, 'sex' => 0])->andWhere(['not in', 'id', $exists])->asArray()->all();
                 }
                 if (count($query) <= 2) {

                     Yii::$app->db->createCommand("update pre_flop_limit_wei set status=0 where openid='{$openid}'")->execute();
                 }
                 $query = $query[mt_rand(0,count($query)-1)];
                 }*/
                if (count($query) <= 2) {
                    Yii::$app->db->createCommand("update pre_flop_limit_wei set status=0 where openid='{$openid}'")->execute();
                }
                $query = $query[mt_rand(0, count($query) - 1)];
            }
            $models = CollectingFilesText::findOne($query['number']);
            if (!empty($models)) {

                echo <<<EOF
    
    <div class='demo__card'>
        <div class='member__id hide'>$query[id]</div>
        <div class='demo__card__top brown'>
            <a class='flop__img_tan' href='/flop/show-msg/?number=$query[number]&id=$query[id]' data-path=$query[content] data-title='编号:$query[number]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$query[weight]kg/$query[height]cm'>
                <div class='demo__card__img' style='background-image: url($pre_url$query[content]);background-size: cover;background-position: center;background-repeat: no-repeat;position: relative;'></div>
            </a>
            <div class='demo__card__info' style='padding:10px;'>
                <div class='pull-left'>
                    <span>编号：$query[number]</span>
                </div>
                <div class='pull-right'>
                    <span>点击图片看大图</span>
                </div>
            </div>
        </div>
    </div>
EOF;
            } else {
                echo <<<EOF
    
    <div class='demo__card'>
        <div class='member__id hide'>$query[id]</div>
        <div class='demo__card__top brown'>
            <a class='flop__img_tan' href=$pre_url$query[content] data-lightbox='dd' data-path=$query[content] data-title='编号:$query[number]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$query[weight]kg/$query[height]cm'>
                <div class='demo__card__img' style='background-image: url($pre_url$query[content]);background-size: cover;background-position: center;background-repeat: no-repeat;position: relative;'></div>
            </a>
            <div class='demo__card__info' style='padding:10px;'>
                <div class='pull-left'>
                    <span>编号：$query[number]</span>
                </div>
                <div class='pull-right'>
                    <span>点击图片看大图</span>
                </div>
            </div>
        </div>
    </div>
EOF;
            }
        }
    }

    public function actionArea(){

        $openid = Yii::$app->request->get('openid');
        $weiUser = (new Query())->from('pre_flop_wei_user')->where(['openid'=>$openid])->one();
        if(empty($weiUser)){
            Yii::$app->session->setFlash('skip_teach','skip_teach');
            Yii::$app->db->createCommand()->insert('pre_flop_wei_user',['openid'=>$openid])->execute();
            return $this->render('flop-teach',['web_url'=>$this->web_url,'openid'=>$openid,]);
        }

        if(!Yii::$app->session->isActive){Yii::$app->session->open();}
        $checkEvaluate = self::checkEvaluate($this->openid);
        if(!empty($checkEvaluate)&&!Yii::$app->session->get('skip_teach')){
            Yii::$app->session->set('skip_teach','skip_teach');
            return $this->redirect('comments?openid='.$openid);
        }

        $address = new Address();
        $local =  $address->getAddress();
        $exec = Yii::$app->db->createCommand("select * from {{%flop}} where area='$local' and sex=0")->queryOne();
        $flopData = new FlopContentDataWei();
        $count = $flopData::find()->where(['openid'=>$openid,'flag'=>$this->flag])->count();

        if(isset($_GET['area'])){
            $yan = new FlopYanZhen();
            $local = $_GET['area'];
            $bi = new BiHua();

            if(isset($_SESSION['password'])&&$_SESSION['password']==$bi->find($local)){

                return $this->render('index',
                    [
                        'area'=>$local,
                        'web_url'=>$this->web_url,
                        'count'=>$count,
                        'openid'=>$openid,
                    ]
                );
            }

            if($yan->load(Yii::$app->request->post())){

                $res = Yii::$app->request->post()['FlopYanZhen']['password'];

                if($yan->validate()&&($res==$bi->find($local))){

                    $_SESSION['password']=$bi->find($local);

                    return $this->render('index',
                        [
                            'area'=>$local,
                            'web_url'=>$this->web_url,
                            'count'=>$count,'openid'=>$openid,
                        ]
                    );
                }
            }

            return $this->render('yan-zhen',
                ['model'=>$yan,'local'=>$local,'web_url'=>$this->web_url,]
            );
        }

        if(empty($local)||empty($exec)){

            return $this->redirect('area-choice');

        }else{

            return $this->render('index',
                [
                    'area'=>$local,
                    'web_url'=>$this->web_url,
                    'count'=>$count,'openid'=>$openid,
                ]
            );
        }
    }

    public function actionFlopNope($id){
        $openid = Yii::$app->request->get('openid');
        if(empty($id)){return ;}

        Yii::$app->db->createCommand("insert into {{%flop_limit_wei}} (openid,flop_id,status) VALUES('$openid',$id,1)")->execute();
        Yii::$app->db->createCommand("update {{%flop_content}} set nope_count=nope_count+1 where id=$id")->execute();
    }

    public function actionFlopLike($id){
        $openid = Yii::$app->request->get('openid');
        if(empty($id)){return ;}

        Yii::$app->db->createCommand("insert into {{%flop_limit_wei}} (openid,flop_id,status) VALUES('$openid',$id,1)")->execute();
        Yii::$app->db->createCommand("update {{%flop_content}} set like_count=like_count+1 where id=$id")->execute();
    }



    public function actionAddFlopList($priority=null){

        $openid = Yii::$app->request->get('openid');
        if(empty($priority)){
            return ;
        }

        $flopData = new FlopContentDataWei();

        $img = (new Query())->select('path')->from('pre_flop_content')->where(['id'=>$priority])->one();

        $query = $flopData::find()->where(['openid'=>$openid,'flag'=>$this->flag,'priority'=>$priority])->one();

        if(empty($query)){

            $flopData->openid = $openid;
            $flopData->priority = $priority;
            $flopData->flag = $this->flag;
            $flopData->img = $img['path'];

            $flopData->save();
        }

        $count = $flopData::find()->where(['openid'=>$openid,'flag'=>$this->flag])->count();
        return '+'.$count;
    }

    public function actionDelete($id,$flag){

        $openid = Yii::$app->request->get('openid');
        if($this->flag!==$flag){

            return;
        }
        $data = $this->findModel($id);
        $data->delete();
        Yii::$app->session->setFlash('skip_teach','skip_teach');
        return $this->redirect($this->web_url.'flop-list?flag='.$flag.'&openid='.$openid);
    }

    public function actionPriority($id){
        $openid = Yii::$app->request->get('openid');
        $priority = (new Query())->select('status')->from('{{%flop_content_data_wei}}')->where(['flag'=>$this->flag,'priority'=>$id])->one();

        $status = $priority['status']==1?0:1;

        Yii::$app->db->createCommand()->update('{{%flop_content_data_wei}}',['status'=>$status],['flag'=>$this->flag,'priority'=>$id])->execute();
    }

    public function actionClearFlop(){

        $cookies = Yii::$app->response->cookies;
        $cookie = Yii::$app->request->cookies;
        Yii::$app->db->createCommand()->update('pre_flop_content_data_wei',['share'=>1],['flag'=>$cookie->getValue('flag2')])->execute();
        $cookies->remove('flag2');
        Yii::$app->session->setFlash('skip_teach','skip_teach');
        return $this->redirect('wei-flop');
    }

    public function actionTeach(){

        $openid = Yii::$app->request->get('openid');
        Yii::$app->session->setFlash('skip_teach','skip_teach');
        return $this->render('flop-teach',['web_url'=>$this->web_url,'openid'=>$openid,]);
    }

    function findModel($id){

        if(($model = FlopContentDataWei::findOne($id))!==null){
            return $model;
        }
    }


}
