<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/1/13
 * Time: 9:58
 */

namespace api\modules\v9\controllers;

use api\modules\v5\models\User;
use api\modules\v9\models\TurnOverCardSuccess;
use Yii;
use yii\data\ActiveDataProvider;
use yii\myhelper\Response;
use yii\rest\ActiveController;

class TurnOverCardMatchController extends ActiveController
{
    public $modelClass = 'api\modules\v9\models\TurnOverCard';
    public $serializer = [
        'class' =>  'yii\rest\Serializer',
        'collectionEnvelope'    => 'items',
    ];

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $action =  parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index'],$action['view'],$action['delete'],$action['update'],$action['create']);
        return $action;
    }

    public function actionView($id){

        $userInfo = User::find()->where(['id'=>$id])->one();
        if(!$userInfo['groupid']){
            Response::show('201','用户不存在');
        }

        $query = TurnOverCardSuccess::find()->select("*");//->select("*,DATE_FORMAT(created_at,'%Y年%m月')")

        //查看匹配成功的  （+评论）
        //$query->Where(['user_id'=>$id])->orWhere(['beliked'=>$id])->andWhere(['flag'=>0])->orderBy('created_at desc');
        $query->Where(['user_id'=>$id])->orWhere(['beliked'=>$id])->andWhere(['flag'=>0])
            ->groupBy('created_at')->addGroupBy("updated_at")->orderBy('created_at desc')->addOrderBy('updated_at desc');


        return new ActiveDataProvider([
            'query'         =>  $query,
            'pagination'    =>  [
                'pageSize'  =>  10,

            ],
            'sort'  =>  [
                'defaultOrder'   => [
                    'id'    =>  SORT_DESC,
                    'updated_at'    =>  SORT_DESC,
                ]
            ]
        ]);
    }
}