<?php
namespace api\modules\v8\controllers;

use Yii;
use yii\helpers\Response;
use yii\rest\ActiveController;
use yii\web\NotFoundHttpException;

class HxGroupController extends ActiveController{

    public $modelClass = 'api\modules\v8\models\HxGroup';

    public function behaviors()
    {
        $behaviors =  parent::behaviors(); // TODO: Change the autogenerated stub
        return $behaviors;
    }

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index'],$actions['view'],$actions['update'],$actions['delete'],$actions['create']);
        return $actions;
    }

    public function actionIndex(){

        $model = new $this->modelClass();
        $info= $model->find()->where([])->all();
        if(!empty($info)){
            $str = [
                'code'  =>  '200',
                'msg'   =>  'success',
                'data'  =>  $info
            ];
            return  $str;
        }else{
            Response::show('201','error','no record');
        }

    }

    public function actionView($id){

        $model = $this->findModel($id);
        if(!empty($model)){

            $str = [
                'code'  =>  '200',
                'msg'   =>  'success',
                'data'  =>  $model
            ];
            return  $str;
        }else{
            Response::show('201','error','no record');
        }

    }


    public function findModel($id){

        $modelClass = $this->modelClass;
        if(($model = $modelClass::findOne(['id'=>$id])) != null){
            return $model;
        }else{
            throw new NotFoundHttpException("The requested page does not exist.");
        }
    }

}