<?php
namespace api\modules\v8\controllers;

use Yii;
use yii\helpers\Response;
use yii\myhelper\Easemob;
use yii\rest\ActiveController;
use yii\web\NotFoundHttpException;

class HxGroup2Controller extends ActiveController{

    public $modelClass = 'api\modules\v8\models\HxGroup';

    public function behaviors()
    {
        $behaviors =  parent::behaviors(); // TODO: Change the autogenerated stub
        return $behaviors;
    }

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index'],$actions['view'],$actions['update'],$actions['delete'],$actions['create']);
        return $actions;
    }

    public function actionView($id){
        $model = $this->findModel($id);
        if(!empty($model)){
            $eason = $this->getMsg()->getGroupDetial($model['g_id']);
            $eason['thumb'] = $model['thumb'];
            return $eason;
        }else{
            Response::show('201','error','no record');
        }
    }

    public function actionIndex(){

        $modelclass = $this->modelClass;
        $ids = json_decode($_GET['groupid']);
        $ids = implode(',',$ids);
        $model = $modelclass::find()->where( "g_id in ({$ids})")->all();

        if(!empty($model)){
            $data = array();
            foreach($model as $list){
                $data[] = $list;
            }

            $str = array(
                'code' => '200',
                'msg' => '操作成功',
                'data' => $data,
            );
            return $str;
        }else{
            Response::show('201','error','no record');
        }

    }


    public function findModel($id){

        $modelClass = $this->modelClass;
        if(($model = $modelClass::findOne(['id'=>$id])) != null){
            return $model;
        }else{
            throw new NotFoundHttpException("The requested page does not exist.");
        }
    }

    public function getMsg(){

        $config = [
            'client_id' =>  Yii::$app->params['client_id'],
            'client_secret' =>  Yii::$app->params['client_secret'],
            'org_name' =>  Yii::$app->params['org_name'],
            'app_name' =>  Yii::$app->params['app_name'],
        ];

        $e = new Easemob($config);
        return $e;
    }

}