<?php

namespace api\modules\v8\controllers;

use api\modules\v5\models\User;
use api\modules\v8\models\Order;
use common\components\SaveToLog;
use yii;
use yii\rest\ActiveController;
use api\modules\v6\models\MemberSort;
use api\modules\v4\models\PredefinedJiecaoCoin;

class MemberSort2Controller extends ActiveController
{

    public $modelClass = 'api\modules\v6\models\Member';
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $actions =  parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index'],$actions['view'],$actions['create'],$actions['update'],$actions['delete']);
        return $actions;
    }

    public function actionView($id){


        $res = (new PredefinedJiecaoCoin())->find()->where(['type'=>1,'member_type'=>0,'status'=>10])->orderBy('money asc')->all();
        $res2 = (new yii\db\Query())->select('jiecao_coin')->from('{{%user_data}}')->where(['user_id'=>$id])->one();
        $data = array();
        $data['jiecao_coin'] = $res2['jiecao_coin'];
        array_fill_keys($data,$res2['jiecao_coin']);
        $data['member'] = $res;
        $data['is_status'] = 0; //1审核环境；0生产环境
        return $data;
    }

    public function actionIndex(){

        $uid = $_GET['uid'];
        $level = (new User())->find()->select('groupid')->where(['id'=>$uid])->one();
        $result = (new MemberSort())->find()->where(['flag'=>1])->orderby(' id DESC ')->all();
        $lunbo = (new yii\db\Query())->from('{{%app_lunbo}}')->where('')->all();
        //审核状态 1 ，生产状态 0
        $status = 0;

        if($status == 1){
            for($i = 0 ; $i < count($result); $i ++){
                if($i == 0){
                    $result[0]['price_1'] = 4998;
                    $result[0]['giveaway'] = 1880;
                }else if($i == 1){
                    $result[1]['price_1'] = 1998;
                    $result[1]['giveaway'] = 990;
                }
            }
        }
        $str = array(
            'user_level'    =>  $level['groupid'],
            'member' => $result,
            'is_status' => $status,
            'lunbo' =>  $lunbo,
        );
        return $str;
    }

}