<?php

namespace api\modules\v7\controllers;

use Yii;
use yii\helpers\Response;
use yii\rest\ActiveController;

class AccusationController extends ActiveController
{

    public  $modelClass = 'api\modules\v7\models\Accusation';
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $action = parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index'],$action['view'],$action['create'],$action['update'],$action['delete']);
        return $action;
    }

    public function actionCreate(){

        $model = new $this->modelClass();
        $model->load(Yii::$app->getRequest()->getBodyParams(),'');
        if($model->save()){
            Response::show('200','操作成功','举报成功');
        }else{
            Response::show('201','操作失败','举报失败');
        }
    }
}