<?php

namespace api\modules\v7\controllers;

use api\modules\v5\models\User;
use api\modules\v6\models\Word;
use backend\modules\setting\models\AppPush;
use yii;
use yii\helpers\Response;
use yii\rest\ActiveController;
use api\modules\v7\models\Message;
use api\modules\v7\models\Like;

class LikeController extends ActiveController
{

    public $modelClass = 'api\modules\v7\models\Like';
    public $serializer = [
        'class'     =>  'yii\rest\Serializer',
        'collectionEnvelope' => 'items'
    ];

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index'],$actions['view'],$actions['create'],$actions['update'],$actions['delete']);
    }

    public function actionIndex(){

        $words_id = isset($_GET['words_id'])?$_GET['words_id']:'';
        if(!$words_id){
            Response::show('201','操作错误','参数不全');
        }
        $model = $this->modelClass;
        $query = $model::find()->where(['words_id'=>$words_id]);

        return new yii\data\ActiveDataProvider([
            'query' =>  $query,
            'pagination'    =>  [
                'pagesize'  =>  15,
            ],
            'sort'  =>  [
                'defaultOrder'  =>  [
                    'id'    =>  SORT_DESC,
                    'updated_at'    =>  SORT_DESC,
                ]
            ],
        ]);
    }

    protected function getUsername($id){

        $userInfo = \api\modules\v4\models\User::find()->where(['id'=>$id])->one();
        if(empty($userInfo['nickname'])){
            $userInfo['nickname'] = $userInfo['username'];
        }
        return $userInfo['nickname'];
    }

    public function actionCreate(){

        $model = new $this->modelClass();
        $model->load(Yii::$app->getRequest()->getBodyParams(),'');
        $re = Word::find()->where(['id'=>$model->words_id])->one();
        if(!$re['id']){
            Response::show('201','操作失败','该帖子不存在');
        }
        //是否取消点赞
        $liked = Like::find()->where(['words_id'=>$model->words_id,'user_id'=>$model->user_id])->one();
        if(!$liked){
            if(!$model->save()){

                Response::show('201','操作失败','点赞失败');
            }else{

                $username = $this->getUsername($model->user_id);

                //添加消息提醒
                $message = new Message();
                $message->from_id =$model->user_id;
                $message->words_id =$model->words_id;
                $message->action = 1;
                $info = Word::find()->where(['id'=>$message->words_id])->one();
                $message->to_id = $info['user_id'];
                $message->save();


                //消息推送(自己给自己点赞不推送)
                $user_id = Word::find()->where(['id'=>$model->words_id])->one();
                if($user_id['user_id'] != $model->user_id){
                    $cid = User::find()->where(['id'=>$user_id['user_id']])->one();
                    if($cid['cid']){
                        $push = new AppPush();
                        $push->title = $username.' 点了个赞';
                        $push->cid = $cid['cid'];
                        $push->type = 'SSCOMM_NEWSCOMMENT_DETAIL';
                        $push->platform = 'all';
                        $push->status = 2;
                        $push->msg = $username.' 点了个赞';
                        $push->message_id = $message->attributes['id'];
                        $push->response = 'NULL';
                        $push->icon = Yii::$app->params['icon'].'/images/app_push/u=1630850300,1879297584&fm=21&gp=0.png';
                        $push->extras = json_encode(array('push_title'=>urlencode($push->title),'push_content'=>urlencode($push->msg),'push_post_id'=>$model->words_id,'push_type'=>'SSCOMM_NEWSCOMMENT_DETAIL'));
                        $push->save();
                        //Yii::$app->db->createCommand("insert into {{%app_push}} (type,status,cid,message_id,title,msg,extras,platform,response,icon,created_at,updated_at) values('SSCOMM_NEWSCOMMENT_DETAIL',2,'$cid[cid]','$message_id','$title','$msg','$extras','all','NULL','$icon',$date,$date)")->execute();
                    }
                }
                Response::show('200','操作成功','点赞成功');
            }
        }else{
            $res = Yii::$app->db->createCommand("delete from pre_app_words_like where words_id={$model->words_id} and user_id = {$model->user_id}")->execute();
            if($res){

                $from_id = $model->user_id;
                $words_id = $model->words_id;

                $message_id = Message::find()->where(['words_id'=>$words_id,'action'=>1])->all();
                if($message_id){
                    $data = array();
                    foreach($message_id as $list){
                        $data[] = $list['id'];
                    }
                    $data = implode(',',$data);
                    //取消点赞时，删除该条消息推送
                    Yii::$app->db->createCommand("delete from pre_app_push where message_id in ({$data})")->execute();
                }

                //取消点赞时，取消该条点赞消息提醒
                Yii::$app->db->createCommand("delete from pre_app_message where from_id = {$from_id} and words_id = {$words_id} and action = 1 ")->execute();
                Response::show('202','操作成功','取消点赞');
            }else{
                Response::show('201','操作失败','取消点赞失败');
            }
        }
    }

    public function actionUpdate($id){

        $ids = array();
        $msg = '欢迎使用我们的app,有什么疑问可以咨询我';
        $ids[] = $id;
        $data['target_type']= 'users';
        $data['target'] = $ids;
        $data['msg'] = ['type'=>'txt','msg'=>$msg];
        $data['from'] = 'ngsn';//shisan-kefu
        return $this->setMes()->sendText($data);

    }

    protected function findModel($id)
    {
        $modelClass = $this->modelClass;
        if (($model = $modelClass::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    //环信信息
    protected function setMes(){

        $options = array(
            'client_id'  => Yii::$app->params['client_id'],   //你的信息
            'client_secret' => Yii::$app->params['client_secret'],//你的信息
            'org_name' => Yii::$app->params['org_name'],//你的信息
            'app_name' => Yii::$app->params['app_name'] ,//你的信息
        );
        $e = new yii\myhelper\Easemob($options);
        return $e;
    }

}