<?php
namespace api\modules\v7\controllers;

use yii\rest\ActiveController;
use yii;
class PredefinedJiecaoCoinController extends ActiveController
{

    public $modelClass = 'api\modules\v4\models\PredefinedJiecaoCoin';

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $actions =  parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index'],$actions['view'],$actions['create'],$actions['update'],$actions['delete']);
        return $actions;
    }

    public function actionIndex(){

        $uid = $_GET['uid'];
        $res = (new $this->modelClass())->find()->where(['type'=>1,'member_type'=>0,'status'=>10])->orderBy('money asc')->all();
        $res2 = (new yii\db\Query())->select('jiecao_coin')->from('{{%user_data}}')->where(['user_id'=>$uid])->one();
        $data = array();
        $data['jiecao_coin'] = $res2['jiecao_coin'];
        array_fill_keys($data,$res2['jiecao_coin']);
        $data['member'] = $res;
        $data['is_status'] = 0; //1审核环境；0生产环境
        return $data;
    }
}