<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/23
 * Time: 10:22
 */

namespace api\modules\v10\controllers;

use Yii;
use yii\myhelper\Decode;
use yii\myhelper\Response;
use yii\rest\Controller;

class AccusationController extends Controller
{

    public  $modelClass = 'api\modules\v7\models\Accusation';
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $action = parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index'],$action['view'],$action['create'],$action['update'],$action['delete']);
        return $action;
    }

    public function actionCreate(){

        $model = new $this->modelClass();
        $model->load(Yii::$app->getRequest()->getBodyParams(),'');
        $decode = new Decode();
        if(!$decode->decodeDigit($model->user_id)){
            Response::show(210,'参数不正确');
        }
        if($model->save()){
            Response::show('200','操作成功','举报成功');
        }else{
            Response::show('201','操作失败','举报失败');
        }
    }
}