<?php

namespace api\modules\v10\controllers;

use backend\modules\app\models\UserImage;
use Yii;
use yii\db\Query;
use yii\myhelper\Decode;
use yii\myhelper\Response;
use yii\rest\Controller;
use yii\web\NotFoundHttpException;

class UserController extends Controller
{

    public $modelClass = 'api\modules\v2\models\Profile';

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $actions = parent::actions();
        unset($actions['index'],$actions['update'],$actions['view'],$actions['create'],$actions['delete']);
        return $actions;
    }

    public function actionView($id){

        $decode = new Decode();
        if(!$decode->decodeDigit($id)){
            Response::show(210,'参数不正确');
        }
        $userInfo = (new Query())->from('{{%user}}')
            ->select('nickname,sex,avatar,address,birthdate')
            ->leftJoin('{{%user_profile}}','pre_user.id=pre_user_profile.user_id')->where(['pre_user.id'=>$id])->one();

        $useImage = UserImage::find()->where(['user_id'=>$id])->asArray()->one();

        if(empty($userInfo['nickname']) || empty($userInfo['avatar']) || empty($userInfo['birthdate']) || empty($userInfo['address']) || empty($useImage['img_url'])){
            Response::show('201','信息不完善，请先填写你的信息');
        }
        Response::show('200','信息完善');

    }

    public function actionUpdate($id)
    {

        $decode = new Decode();
        if(!$decode->decodeDigit($id)){
            Response::show(210,'参数不正确');
        }
        $model = $this->findModels($id);

        $model->load(Yii::$app->getRequest()->getBodyParams(), '');

        if (!$model->save()) {
            Response::show(201,'更新失败');
        }else{
            Response::show(202,'更新成功');
        }
    }

    public function actionDelete($id){

        $decode = new Decode();
        if(!$decode->decodeDigit($id)){
            Response::show(210,'参数不正确');
        }
        $model = (new Query())->select('cid')->from('{{%user}}')->where(['id'=>$id])->one();
        if($model['cid']){
            $res = Yii::$app->db->createCommand("update pre_user set cid = '' where id ={$id}")->execute();
            if($res){
                Response::show('200','操作成功','cid置空成功');
            }
            Response::show('202','操作失败',"cid置空失败");
        }
        Response::show('201','操作失败','该用户没有cid');
    }

    protected function findModels($id){

        $modelClass = $this->modelClass;

        if (($model = $modelClass::find()->where('user_id=:user_id',[':user_id'=>$id])->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }



}