<?php
namespace api\modules\v11\models;

use api\modules\v9\models\UserProfile;
use app\components\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use Yii;
/**
 * This is the model class for table "pre_app_form_thread_comments".
 *
 * @property integer $comment_id
 * @property integer $thread_id
 * @property string $comment
 * @property integer $updated_at
 * @property integer $created_at
 * @property integer $flag
 * @property integer $first_id
 * @property integer $second_id
 */
class FormThreadComments extends ActiveRecord
{
    private $_first;
    private $_second;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%app_form_thread_comments}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['thread_id', 'comment','first_id'], 'required'],
            [['thread_id', 'created_at', 'flag','updated_at','first_id','second_id'], 'integer'],
            [['comment'], 'string']
        ];
    }

    public function fields(){

        $this->_first = User::findOne(['id'=>$this->first_id]);
        $this->_second = User::findOne(['id'=>$this->second_id]);

        $data = array(
            'comment_id','words_id'=>'thread_id', 'comment', 'created_at','updated_at', 'flag',
            'first_id'=>function(){

                return "$this->first_id";
            },
            'second_id'=>function(){

                return "$this->second_id";
            },
            'firstUrl'=>function(){
                return $this->_first->avatar;
            },
            'firstName'=>function(){
                return empty($this->_first->nickname)?$this->_first->username:$this->_first->nickname;
            },
        );

        if(!empty($this->_second)){
            $data['secondUrl'] = function (){return $this->_second->avatar;};
            $data['secondName'] = function (){return empty($this->_second->nickname)?$this->_second->username:$this->_second->nickname;};
        }

        return $data;
    }

    protected function config(){

        Yii::setAlias('@apppush','@backend/apppush');
        $path = Yii::getAlias('@apppush');
        require_once ($path.'/demo.php');
        //http的域名
        define('HOST','http://sdk.open.api.igexin.com/apiex.htm');

        //https的域名
        //define('HOST','https://api.getui.com/apiex.htm');

        define('APPKEY',Yii::$app->params['geAPPKEY']);
        define('APPID',Yii::$app->params['geAPPID']);
        define('MASTERSECRET',Yii::$app->params['geMASTERSECRET']);

        // define('DEVICETOKEN','');
        // define('Alias','请输入别名');
        //define('BEGINTIME','2015-03-06 13:18:00');
        //define('ENDTIME','2015-03-06 13:24:00');


    }
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        $this->config();
        $title='d';
        $msg='您的朋友圈有回复哦';
        $extras = "{'push_title':'fwaef','push_content':'fawe','push_type':'SSCOMM_NOTICE'}";

        $cids = ['2380569401cb7db1834eb482793a0321','b664092c0fbac653e450dd386acbefc5'];

        //define('CID',$model['cid']);

        $model = self::find()->where(['thread_id'=>$this->thread_id])->andWhere("first_id!=$this->first_id")->asArray()->all();
        pushMessageToList(2, $msg , $extras , $title , $cids);
        return var_dump(ArrayHelper::map($model,'first_id','first_id'));
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'comment_id' => 'Comment ID',
            'thread_id' => 'Thread ID',
            'comment' => 'Comment',
            'first_id'=>'First ID',
            'second_id'=>'Second ID',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
            'flag' => 'Flag',
        ];
    }

}
