<?php
namespace api\modules\v11\models;

use app\components\db\ActiveRecord;
use app\components\PushConfig;
use yii\helpers\ArrayHelper;
/**
 * This is the model class for table "pre_app_form_thread_thumbs_up".
 *
 * @property integer $thumbs_id
 * @property integer $thread_id
 * @property integer $user_id
 * @property integer $created_at
 * @property integer $updated_at
 */
class FormThreadThumbsUp extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%app_form_thread_thumbs_up}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['thread_id', 'user_id'], 'required'],
            [['thread_id', 'user_id', 'created_at','updated_at'], 'integer'],
            ['thread_id','unique'],
        ];
    }
    public function unique(){
        $query = $this->findOne(['thread_id'=>$this->thread_id,'user_id'=>$this->user_id]);
        if(!empty($query)){
            $this->addError('user_id', '已经点赞');
        }
    }

    public function fields(){

        return [
            'user_id','created_at','updated_at',
            'avatar'=>function(){
                return User::findOne(['id'=>$this->user_id])->avatar;
            },
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        PushConfig::config();

        $title='朋友圈回复';
        $msg='您的朋友圈有回复哦';
        $extras = "{'push_title':'fwaef','push_content':'fawe','push_type':'SSCOMM_NOTICE'}";

        $tuid = array();
        $cuid = array();
        $model = self::find()->where(['thread_id'=>$this->thread_id])->andWhere("user_id!=$this->user_id")->asArray()->all();
        $commentModel = FormThreadComments::find()->where(['thread_id'=>$this->thread_id])->andWhere("first_id!=$this->user_id")->asArray()->all();
        if(!empty($model)){
            $tuid = ArrayHelper::map($model,'user_id','user_id');
        }
        if(!empty($commentModel)){
            $cuid = ArrayHelper::map($commentModel,'first_id','first_id');
        }
        $uids = array_merge($cuid, $tuid);
        if(!empty($uids)){
            $userCid = array_filter(ArrayHelper::map(User::find()->where(['id'=>$uids])->asArray()->all(),'cid','cid'));
        }else{
            $userCid = "";
        }
        $thread_uid = FormThread::findOne($this->thread_id)->user_id;

        if(!empty($userCid)){
            pushMessageToList(1, $msg , $extras , $title , $userCid);
        }

        $data = array();
        if($this->user_id!=$thread_uid){
            $data = [[$this->thread_id,$thread_uid,$this->user_id,"",time(),time()]];
        }

        foreach ($uids as $uid){
            if($uid!=$thread_uid){
                $da = [$this->thread_id,$uid,$this->user_id,"",time(),time()];
                array_push($data,$da);
            }
        }

        if(!empty($data)){
            \Yii::$app->db->createCommand()->batchInsert('pre_app_form_thread_push_msg', ['wid','user_id','writer_id','content','created_at','updated_at'],$data)->execute();
        }

    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'thumbs_id' => 'Thumbs ID',
            'thread_id' => 'Thread ID',
            'user_id' => 'User ID',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
        ];
    }

}
