<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/8/18
 * Time: 16:23
 */

namespace api\modules\v6\models;

use yii\db\ActiveRecord;
use Yii;

/**
 * This is the model class for table "pre_make_friend".
 * @property integer $id;
 * @property integer $user_id;
 * @property integer $friend_id;
 * @property integer $payfor;
 * @property integer $flag;
 * @property integer $created_at;
 * @property integer $updated_at;
 *
*/
class MakeFriend extends ActiveRecord
{

    public static function tableName()
    {
        return '{{%make_friend}}'; // TODO: Change the autogenerated stub
    }

    public function rules(){

        return [
            [['user_id','friend_id','flag'],'required'],
            [['user_id','friend_id','payfor'],'integer'],
        ];
    }

    public function attributeLabels(){

        return [
            'id'    =>  'ID',
            'user_id'   =>  'user_id',
            'friend_id' =>  'friend_id',
            'flag' =>  'flag',
            'payfor' =>  'payfor',
            'created_at'=>  'created_at',
            'updated_at'=>  'updated_at',
        ];
    }

    public function fields(){

        return [
            'id' ,
            'user_id'  ,
            'friend_id' ,
            'flag',
            'payfor',
            'created_at',
            'updated_at',
        ];
    }


}